name: Build

on:
  push:
    branches:
      - develop

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            persist-credentials: false
            fetch-depth: 0

      - name: Download
        run: |
          curl -s -L https://github.com/getzola/zola/releases/download/v0.11.0/zola-v0.11.0-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin

      - name: Build
        run: zola build

      - name: Commit files
        run: |
          sudo pip install ghp-import
          ghp-import -n public -b master
 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: master
